services:
  db:
    image: mariadb:11.5
    container_name: mariadb
    ports: 
      - "3308:3306"
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PW}
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PW}
    volumes:
      - "storage:/var/lib/mariadb"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
  web:
    container_name: nextjs
    build:
      context: .
      dockerfile: dockerfile
    ports: 
      - "3001:3000"
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy

volumes:
  storage:
    name: "dongarimart-storage"